services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=2
    volumes:
      - ./ollama:/root/.ollama
  hevyzer:
    build: .
    container_name: hevyzer
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    restart: unless-stopped