services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=2
    volumes:
      - ./ollama:/root/.ollama
  hevyzer:
    build: .
    container_name: hevyzer
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - db
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: hevyzer
      POSTGRES_PASSWORD: hevyzer
      POSTGRES_DB: hevyzerdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: