[project]
name = "hevyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "openai>=1.99.9",
    "python-dotenv>=1.1.1",
    "stravalib>=2.4",
    "authlib",
    "sqlalchemy",
    "psycopg2-binary",
    "flask-sqlalchemy"
]
